<?php
/**
 * ExportController.php — ANU Export Engine
 *
 * Responsibilities:
 *   • Stream CSV/JSON exports (memory-efficient, never loads full dataset into array)
 *   • PDF export via jsPDF (triggered client-side for current view)
 *   • Audit every export action to reports_audit table
 *   • Include metadata block in all exports
 *
 * Architecture: Controller layer. Receives validated filters from reports.php,
 *               calls ReportService for data, streams output directly.
 */
class ExportController
{
    private mysqli       $conn;
    private ReportService $svc;

    public function __construct(mysqli $conn, ReportService $svc)
    {
        $this->conn = $conn;
        $this->svc  = $svc;
    }

    // ═══════════════════════════════════════════════════════════════
    // AUDIT LOG — every export call must go through here
    // ═══════════════════════════════════════════════════════════════
    private function logExport(string $format, array $raw_filters, int $record_count = 0): void
    {
        $user_id      = $_SESSION['user_id'] ?? null;
        $ip           = $_SERVER['REMOTE_ADDR'] ?? '0.0.0.0';
        $filters_json = json_encode($raw_filters, JSON_UNESCAPED_UNICODE);

        $stmt = $this->conn->prepare(
            "INSERT INTO reports_audit (user_id, export_format, filters_json, ip_address, record_count)
             VALUES (?, ?, ?, ?, ?)"
        );
        // Gracefully skip if table doesn't exist yet (schema patch not applied)
        if ($stmt) {
            $stmt->bind_param('isssi', $user_id, $format, $filters_json, $ip, $record_count);
            $stmt->execute();
        }
    }

    // ═══════════════════════════════════════════════════════════════
    // METADATA BLOCK — shared across export formats
    // ═══════════════════════════════════════════════════════════════
    private function buildMeta(array $f, int $count): array
    {
        return [
            'system'        => 'ANU Meal Booking System',
            'report_title'  => 'Booking Export Report',
            'generated_at'  => date('Y-m-d H:i:s'),
            'generated_by'  => $_SESSION['fullname'] ?? 'Admin',
            'period_from'   => $f['from'] ?? '',
            'period_to'     => $f['to']   ?? '',
            'filters'       => $f['raw']  ?? [],
            'total_records' => $count,
        ];
    }

    // ═══════════════════════════════════════════════════════════════
    // CSV FULL EXPORT — streamed row-by-row, no memory spike
    // ═══════════════════════════════════════════════════════════════
    public function exportCSV(array $f): void
    {
        $filename = 'anu_bookings_' . date('Y-m-d_His') . '.csv';

        header('Content-Type: text/csv; charset=utf-8');
        header('Content-Disposition: attachment; filename="' . $filename . '"');
        header('Cache-Control: no-store, no-cache');
        header('Pragma: no-cache');

        $out = fopen('php://output', 'w');

        // ── Metadata header block ──
        fputcsv($out, ['ANU Meal Booking System — Booking Export']);
        fputcsv($out, ['Generated by',    $_SESSION['fullname'] ?? 'Admin']);
        fputcsv($out, ['Generated at',    date('d M Y H:i:s')]);
        fputcsv($out, ['Period',          ($f['from'] ?? '') . ' to ' . ($f['to'] ?? '')]);
        fputcsv($out, ['Filters applied', json_encode($f['raw'] ?? [])]);
        fputcsv($out, []);  // blank separator

        // ── Column headers ──
        fputcsv($out, [
            'Booking Code', 'Student Name', 'Student ID', 'Department',
            'Meal Name', 'Meal Type', 'Price (KES)',
            'Meal Date', 'Status',
            'Booked At', 'Validated At', 'Validated By'
        ]);

        // ── Stream rows — never loads full result into memory ──
        $result = $this->svc->getExportResult($f);
        $count  = 0;
        while ($row = $result->fetch_assoc()) {
            fputcsv($out, [
                $row['code'],
                $row['fullname'],
                $row['student_id']     ?? '',
                $row['department']     ?? '',
                $row['meal_name'],
                $row['meal_type'],
                number_format((float)$row['price'], 2),
                $row['date']           ? date('d/m/Y', strtotime($row['date'])) : '',
                strtoupper($row['status']),
                $row['created_at']     ? date('d/m/Y H:i', strtotime($row['created_at']))  : '',
                $row['validated_at']   ? date('d/m/Y H:i', strtotime($row['validated_at'])): '',
                $row['validator_name'] ?? '',
            ]);
            $count++;
        }

        // ── Footer ──
        fputcsv($out, []);
        fputcsv($out, ['Total Records', $count]);

        fclose($out);
        $this->logExport('csv', $f['raw'] ?? [], $count);
        exit;
    }

    // ═══════════════════════════════════════════════════════════════
    // CSV SUMMARY EXPORT — stats only, no row data
    // ═══════════════════════════════════════════════════════════════
    public function exportSummaryCSV(array $f, array $stats): void
    {
        header('Content-Type: text/csv; charset=utf-8');
        header('Content-Disposition: attachment; filename="anu_summary_' . date('Y-m-d') . '.csv"');
        header('Cache-Control: no-store');

        $out = fopen('php://output', 'w');
        fputcsv($out, ['ANU Meal Booking System — Summary Report']);
        fputcsv($out, ['Period',       ($f['from'] ?? '') . ' to ' . ($f['to'] ?? '')]);
        fputcsv($out, ['Generated',    date('d M Y H:i:s')]);
        fputcsv($out, ['Generated by', $_SESSION['fullname'] ?? 'Admin']);
        fputcsv($out, []);

        fputcsv($out, ['Metric', 'Value']);
        fputcsv($out, ['Total Bookings',    $stats['total']]);
        fputcsv($out, ['Consumed',          $stats['consumed']]);
        fputcsv($out, ['Approved',          $stats['approved']]);
        fputcsv($out, ['Pending',           $stats['pending']]);
        fputcsv($out, ['Rejected',          $stats['rejected']]);
        fputcsv($out, ['Total Revenue',     'KES ' . number_format($stats['revenue'], 2)]);
        fputcsv($out, ['Average Price',     'KES ' . number_format($stats['avg_price'], 2)]);
        fputcsv($out, ['Approval Rate',     $stats['approval_rate']    . '%']);
        fputcsv($out, ['Consumption Rate',  $stats['consumption_rate'] . '%']);
        fputcsv($out, ['Rejection Rate',    $stats['rejection_rate']   . '%']);

        fclose($out);
        $this->logExport('csv_summary', $f['raw'] ?? [], 0);
        exit;
    }

    // ═══════════════════════════════════════════════════════════════
    // JSON EXPORT — API-ready endpoint
    // ═══════════════════════════════════════════════════════════════
    public function exportJSON(array $f): void
    {
        header('Content-Type: application/json; charset=utf-8');
        header('Content-Disposition: attachment; filename="anu_report_' . date('Y-m-d_His') . '.json"');
        header('Cache-Control: no-store');

        $result = $this->svc->getExportResult($f);
        $rows   = [];
        while ($row = $result->fetch_assoc()) {
            $rows[] = $row;
        }

        $output = [
            'meta' => $this->buildMeta($f, count($rows)),
            'data' => $rows,
        ];

        echo json_encode($output, JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE);
        $this->logExport('json', $f['raw'] ?? [], count($rows));
        exit;
    }
}
